### ISSUE TITLE
Account activation link to be changed as button 

### ISSUE THREAD

**Issue by MuzaffarMohammed** [MuzaffarMohammed/kfmenterprises-ecommerce#24]
![image](https://user-images.githubusercontent.com/50576677/127004160-72af3f46-9ff4-4cf3-af1f-c31a52e34625.png)

In mail, this link should be replaced with button 'Activate Now'.

This is add security by hiding the link.

**Comment by MohammedHabeebkhan** [comment]
This Issue has been solved with issue# 29 and 33.
