### ISSUE TITLE
Timestamp to be added on order detail page for users and admin

### ISSUE THREAD

**Issue by MuzaffarMohammed** [MuzaffarMohammed/kfmenterprises-ecommerce#30]
![image](https://user-images.githubusercontent.com/50576677/127011344-18cddff2-a1aa-42ed-b2fe-49710040b979.png)

Acceptance Criteria:
1. Date and time to be present at each status bar for admin and user to have knowledge on order placement.

**Comment by MohammedHabeebkhan** [comment]
"Order PlaceAt" label changed to "Order Date"  
and in the shopiing cart have restricted enter to refresh the page and make enter the to check the empty fields the form to check before proceed to pay. if each filed is filled then enter key takes the user to the next payment page.
