### ISSUE TITLE
Date corrections on order page fpr user and admin

### ISSUE THREAD

**Issue by MuzaffarMohammed** [MuzaffarMohammed/kfmenterprises-ecommerce#32]
![image](https://user-images.githubusercontent.com/50576677/127013998-29502ff5-e373-4d27-80a3-95c99470dea1.png)

Acceptance Criteria: 
1. Proper dates for GMT + 5:30 to be added.

**Comment by MohammedHabeebkhan** [comment]
Changes has been done and Tested in Dev. Ready to move in Production.

**Comment by MohammedHabeebkhan** [comment]
Changes has been done and Tested in Dev. Ready to move in Production.
