### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by MuzaffarMohammed** [MuzaffarMohammed/kfmenterprises-ecommerce#6]
Validate all screens and furnish the UI where ever is needed.

@MohammedHabeebkhan

**Comment by MuzaffarMohammed** [comment]
@MohammedHabeebkhan Add cursor as pointer when hover on BEST SELLING PRODUCTS each icon.

**Comment by MuzaffarMohammed** [comment]
![image](https://user-images.githubusercontent.com/50576677/126995401-f09fc26f-e0b7-4af6-8eed-6ff1555e2814.png)

@MohammedHabeebkhan  these two blocks should have equal adjacent corners at both sides.

**Comment by MuzaffarMohammed** [comment]
![image](https://user-images.githubusercontent.com/50576677/126996922-9036d51c-2cae-4a07-870b-59150edcbb53.png)

@MohammedHabeebkhan  Products to be renamed to 'Add Product'

**Comment by MuzaffarMohammed** [comment]
![image](https://user-images.githubusercontent.com/50576677/126997535-682e82cc-345c-45a7-ad93-1c1bc3f6e5da.png)

@MohammedHabeebkhan  Buy button to be disabled to any Admin logins.

Currently, it is showing added to cart when clicked.

Resolution: Button to be disabled when admin logs in.

**Comment by MuzaffarMohammed** [comment]
![image](https://user-images.githubusercontent.com/50576677/126998709-30ef592e-62d3-431f-8c3c-70bac02a5940.png)

@MohammedHabeebkhan  resolution: disable this Actions column for now by commenting in the code. We may later re-use it. so just comment code, don't remove it.

**Comment by MuzaffarMohammed** [comment]
![image](https://user-images.githubusercontent.com/50576677/126999957-69148d02-2933-42de-a46b-a528684eecb5.png)

Resolution: 'All Products' should be changed to 'All'. You must validate and test thoroughly all the places.

**Comment by MuzaffarMohammed** [comment]
![image](https://user-images.githubusercontent.com/50576677/127001007-e8452109-9b95-41f7-9ffc-be9669d35e61.png)
@MohammedHabeebkhan 
Text should be "Only Alphabets, Numbers, and three special characters [ . @ _ ] are allowed in 'User Name'."

**Comment by MohammedHabeebkhan** [comment]
Changes has been done and tested.
